//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOkul.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;
    
    public partial class Tbl_Notlar
    {
        public int NotId { get; set; }
        public Nullable<int> OgrId { get; set; }
        public Nullable<int> DersId { get; set; }
       
        public Nullable<int> Sınav1 { get; set; }
        public Nullable<int> Sınav2 { get; set; }
        public Nullable<int> Sınav3 { get; set; }
        public Nullable<int> Proje { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Dersler Tbl_Dersler { get; set; }
        public virtual Tbl_Ogrenciler Tbl_Ogrenciler { get; set; }
    }
}
